module.exports = {
  index: '熊猫博士看世界',
  account: '个人中心',
  activity: '活动',
  course: '课程详情',
  'account/detail': '我的账户',
  'account/edit': '我的账户',
  'account/faq': 'Q&A',
  'account/voucher': '优惠券',
  'account/order': '我的订单',
  'account/study': '课程列表',
  'account/study/chapter': '课程学习',
  'course/pay': '确认付款',
  'course/paySuccess': '支付成功',
  'course/assembleProgress': '拼团详情',
}
